name: Terraform CI for Dev Environment

on:
  push:
    branches: [dev]
    
  pull_request:
    branches: [dev]
    
jobs:
  terraform-dev:
    name: Terraform Plan + tfsec (Dev)
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-2"
      S3_BUCKET: "tfsec-dev-bucket"
      
    defaults:
      run:
        working-directory: environments/dev
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        
    - name: Terraform Format Check
      run: terraform fmt #-check
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      run: terraform plan
      
    - name: Install tfsec
      run: |
        curl -sSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o tfsec
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/
        
    - name: Run tfsec and generate report
      id: tfsec
      run: |
        tfsec --format json --out tfsec-results.json
        
    - name: Upload tfsec report as artifact
      if: always()  # ensures this runs even if tfsec fails
      uses: actions/upload-artifact@v4
      with:
        name: tfsec-results
        path: environments/dev/tfsec-results.json
        
    - name: Upload tfsec report to S3
      if: always()
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
         # Determine commit ID based on event type
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          COMMIT_ID="${{ github.event.pull_request.head.sha }}"
        else
          COMMIT_ID="${{ github.sha }}"
        fi
        COMMIT_SHORT=${COMMIT_ID::7}
        echo "Uploading with commit ID: $COMMIT_SHORT"
        aws s3 cp tfsec-results.json s3://$S3_BUCKET/tfsec-results-$TIMESTAMP-$COMMIT_SHORT.json
